### ISSUE TITLE
Roadmap December

### ISSUE THREAD

**Issue by edmBernard** [edmBernard/Stryke#1]
Things to do : 
- [x] : add string type
- [x] : add bool type
- [x] : add Date support in multi file
- [x] : add TimestampNumber support in multi file
- [x] : add Timestamp support in multi file
- [x] : add capacity to have null in orc file
- [x] : replace time.h by date.h header library gmtime is note thread safe (fixed python datetime)

Python : 
- [x] : Add python binding
- [x] : Add some standard type :
    - [x] : Point1i<Date, Int, Int>
    - [x] : Point1f<Date, Float Float>
    - [x] : Point2i<Date, Int, Int>
    - [x] : Point2f<Date, Float Float>
    - [x] : Point3i<Date, Int, Int, Int>
    - [x] : Point3f<Date, Float Float, Float>
    - [x] : PointXYZI<Date, Float Float, Float, Float>
    - [x] : Vec2i<Date, Int, Int, Int, Int>
    - [x] : Vec2f<Date, Float, Float, Float, Float>
    - [x] : Vec3i<Date, Int, Int, Int, Int, Int, Int>
    - [x] : Vec3f<Date, Float, Float, Float, Float, Float, Float>

Examples: 
- [x] : Add better examples in C++
- [x] : Add better examples in Python

Tests: 
- [x] : Add Python Tests
- [x] : add basic reader to check file content
- [x] : add basic reader binding to check file content in python
