### ISSUE TITLE
Roadmap April

### ISSUE THREAD

**Issue by edmBernard** [edmBernard/stryke#11]
- [x] : refactor csv writer
- [ ] : move get_time from disptach to type

Reader : 
   - [ ] : Add folder encoded data in data output
   - [ ] : Integrate utils_for_test in reader
   - [ ] : Add error if number of column differ between file and template schema
   - [ ] : Add batch metadata reader
   - [ ] : Add stride metadata reader
   - [ ] : Add range filtering in reader
