### ISSUE TITLE
Roadmap February

### ISSUE THREAD

**Issue by edmBernard** [edmBernard/stryke#5]
Reader:
- [x] : writing in folder name ability (predicate pushdown) 
     - [x] for dispatch writer
     - [x] rework old dispatch as date_dispatch
     - [x] for multifile writer
     - [x] rework old multifile as date_multifile
     - [x] add more test
     - [ ] add test coverage :question:  I don't find coverage for template
- [x] : Add column name reader
- [ ] : Integrate utils_for_test in reader
- [ ] : Add error if number of column differ between file and template schema
- [ ] : Add batch metadata reader
- [ ] : Add stride metadata reader
- [ ] : Add range filtering in reader
